# Node.js CI workflow

name: Node.js CI

on: [push, pull_request, merge_group]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IS_PUSH_MASTER: ${{ github.ref == 'refs/heads/master' }}
      IS_PUSH_TAG: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Run lint
      run: yarn run lint
    - name: Build (if tag or master branch)
      if: env.IS_PUSH_MASTER == 'true' || env.IS_PUSH_TAG == 'true'
      run: |
        rm -Rf ./node_modules/*
        yarn install --prod
        mkdir build
        cp -Rf *.* ./build
        cp -Rf src css ext node_modules resources ./build
    - name: Push to gh-pages (if tag or master branch)
      if: env.IS_PUSH_MASTER == 'true' || env.IS_PUSH_TAG == 'true'
      run: |
        DEPLOY_DIR=./demo/trunk
        if ${{ env.IS_PUSH_TAG }}; then
          DEPLOY_DIR=./demo/stable
        fi
        ALL=/*
        git config user.email github-actions@github.com
        git config user.name github-actions
        git checkout gh-pages
        rm -Rf $DEPLOY_DIR$ALL
        cp -Rf ./build/* $DEPLOY_DIR
        git add -A $DEPLOY_DIR
        git diff-index --quiet HEAD ||
          git commit -m "CI run ${{ github.run_number }} pushed to gh-pages"
        git push -fq origin gh-pages
